# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aC0306_Ba0WllENp_sClyAGH-75ABjzg
"""

!pip3 install earthaccess



import earthaccess

# 1. Login
earthaccess.login()

results = earthaccess.search_data(
    short_name="ATL06",
    cloud_hosted=False,
    temporal=("2019-01", "2019-02"), # time periots
    polygon=[(-100, 40), (-110, 40), (-105, 38), (-100, 40)],
)
results[0]

# fetch the data

!pip install h5py pandas

nsidc_url = "https://n5eil01u.ecs.nsidc.org/DP7/ATLAS/ATL06.005/2019.02.21/ATL06_20190221121851_08410203_005_01.h5"
lpcloud_url = "https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20220903T163129_2224611_012/EMIT_L2A_RFL_001_20220903T163129_2224611_012.nc"

session = earthaccess.get_requests_https_session()

headers = {"Range": "bytes=0-100"}
r = session.get(lpcloud_url, headers=headers)
r

fs = earthaccess.get_fsspec_https_session()

with fs.open(lpcloud_url) as f:
    data = f.read(100)
data

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# import xarray as xr
# 
# files = earthaccess.open(results[0:2])
# 
# ds = xr.open_dataset(files[0], group="/gt1r/land_ice_segments")
# ds

